# Generated by Django 4.0.1 on 2022-02-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_waitlistentry_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Class Level'),
        ),
    ]
