# Generated by Django 4.0.1 on 2022-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(2, 'Level Two'), (1, 'Level One')]),
        ),
    ]
