# Generated by Django 4.0.1 on 2022-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(1, 'Level One'), (2, 'Level Two')]),
        ),
    ]
