# Generated by Django 4.0.1 on 2022-02-04 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(2, 'Level Two'), (1, 'Level One')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
