# Generated by Django 4.0.1 on 2022-02-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecturer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
