# Generated by Django 4.0.1 on 2022-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_lecturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=1, help_text='Enter number of hours'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
